### ISSUE TITLE
NotImplementedError usage

### ISSUE THREAD

**Issue by Kaveshnikov** [xsuchy/python-hwdata#2]
Hi. Why don't you use `NotImplementedError`, for example, here https://github.com/xsuchy/python-hwdata/blob/master/hwdata.py#L107 ?

**Comment by xsuchy** [comment]
Because at the time of writing I did not know it existed. :)

**Comment by Kaveshnikov** [comment]
Well, are you going to use them? Shall I do the PR?

**Comment by xsuchy** [comment]
PR would be very nice and I will happily merge it.

**Comment by xsuchy** [comment]
Fixed in https://github.com/xsuchy/python-hwdata/pull/3
